services:
  mdsite:
    build: .
    container_name: minio-mdsite
    restart: unless-stopped
    env_file: .env
    environment:
      - ES_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "7861:7861"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: mkviewer-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200 >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  es-data:
